version: '3'

services:
  db:
    image: mariadb:10.0
    restart: always
    container_name: 'db'
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - '$MYSQL_PORT'
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'python'
    ports:
      - '$APP_PORT:$APP_PORT'
    env_file:
      - .env
    depends_on:
      - db
    tty: true

volumes:
  db_data:
