"""Add created and updated

Revision ID: 1b2ef673512f
Revises: f94cc58e1479
Create Date: 2022-01-06 00:04:36.562246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2ef673512f'
down_revision = 'f94cc58e1479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('issues', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated')
    op.drop_column('tasks', 'created')
    op.drop_column('issues', 'updated')
    op.drop_column('issues', 'created')
    # ### end Alembic commands ###
