"""Add Issue Title col

Revision ID: f94cc58e1479
Revises: c4d2bb0678c0
Create Date: 2022-01-02 08:01:56.752015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94cc58e1479'
down_revision = 'c4d2bb0678c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('title', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'title')
    # ### end Alembic commands ###
